export interface PlantType {
    codename: string;
    displayName?: string;
}

export const Plants: PlantType[] = [
    { codename: 'sunflower', displayName: 'Sunflower' },
    { codename: 'peashooter', displayName: 'Peashooter' },
    { codename: 'wallnut', displayName: 'Wall-nut' },
    { codename: 'tallnut', displayName: 'Tall-nut' },
    { codename: 'explodeonut', displayName: 'Explode-o-nut' },
    { codename: 'bonkchoy', displayName: 'Bonk Choy' },
    { codename: 'cabbagepult', displayName: 'Cabbage-pult' },
    { codename: 'melonpult', displayName: 'Melon-pult' },
    { codename: 'cherry_bomb', displayName: 'Cherry Bomb' },
    { codename: 'coconutcannon', displayName: 'Coconut Cannon' },
    { codename: 'gravebuster', displayName: 'Gravebuster' },
    { codename: 'iceburg', displayName: 'Iceberg Lettuce' },
    { codename: 'laser_bean', displayName: 'Laser Bean' },
    { codename: 'potatomine', displayName: 'Potato Mine' },
    { codename: 'repeater', displayName: 'Repeater' },
    { codename: 'snapdragon', displayName: 'Snapdragon' },
    { codename: 'spikeweed', displayName: 'Spikeweed' },
    { codename: 'threepeater', displayName: 'Threepeater' },
    { codename: 'torchwood', displayName: 'Torchwood' },
    { codename: 'kernelpult', displayName: 'Kernel-pult' },
    { codename: 'springbean', displayName: 'Spring Bean' },
    { codename: 'snowpea', displayName: 'Snow Pea' },
    { codename: 'chilibean', displayName: 'Chili Pea' },
    { codename: 'splitpea', displayName: 'Split Pea' },
    { codename: 'lightningreed', displayName: 'Lightning Reed' },
    { codename: 'peapod', displayName: 'Pea Pod' },
    { codename: 'magnifyinggrass', displayName: 'Magnifying Grass' },
    { codename: 'bloomerang', displayName: 'Bloomerang' },
    { codename: 'holonut', displayName: 'Infi-nut' },
    { codename: 'empea', displayName: 'E.M.Peach' },
    { codename: 'blover', displayName: 'Blover' },
    { codename: 'starfruit', displayName: 'Starfruit' },
    { codename: 'imitater', displayName: 'Imitater' },
    { codename: 'jalapeno', displayName: 'Jalapeno' },
    { codename: 'wintermelon', displayName: 'Winter Melon' },
    { codename: 'twinsunflower', displayName: 'Twin Sunflower' },
    { codename: 'marigold', displayName: 'Marigold' },
    { codename: 'spikerock', displayName: 'Spikerock' },
    { codename: 'powerlily', displayName: 'Power Lily' },
    { codename: 'squash', displayName: 'Squash' },
    { codename: 'citron', displayName: 'Citron' },
    { codename: 'powerplant', displayName: 'Tile Turnip' },
    { codename: 'sunshroom', displayName: 'Sun-shroom' },
    { codename: 'puffshroom', displayName: 'Puff-shroom' },
    { codename: 'fumeshroom', displayName: 'Fume-shroom' },
    { codename: 'sunbean', displayName: 'Sun Bean' },
    { codename: 'magnetshroom', displayName: 'Magnet-shroom' },
    { codename: 'hypnoshroom', displayName: 'Hypno-shroom' },
    { codename: 'peanut', displayName: 'Peanut' },
    { codename: 'firepeashooter', displayName: 'Fire Peashooter' },
    { codename: 'lilypad', displayName: 'Lilypad' },
    { codename: 'bowlingbulb', displayName: 'Bowling Bulb' },
    { codename: 'homingthistle', displayName: 'Homing Thistle' },
    { codename: 'banana', displayName: 'Banana Launcher' },
    { codename: 'chomper', displayName: 'Chomper' },
    { codename: 'guacodile', displayName: 'Guacodile' },
    { codename: 'tanglekelp', displayName: 'Tangle Kelp' },
    { codename: 'ghostpepper', displayName: 'Ghost Pepper' },
    { codename: 'sweetpotato', displayName: 'Sweet Potato' },
    { codename: 'sapfling', displayName: 'Sap-fling' },
    { codename: 'hurrikale', displayName: 'Hurrikale' },
    { codename: 'xshot', displayName: 'Rotobaga' },
    { codename: 'chardguard', displayName: 'Ghard Guard' },
    { codename: 'pepperpult', displayName: 'Pepper-pult' },
    { codename: 'kiwibeast', displayName: 'Kiwibeast' },
    { codename: 'hotpotato', displayName: 'Hot Potato' },
    { codename: 'stunion', displayName: 'Stunion' },
    { codename: 'sprout', displayName: 'Sprout' },
    { codename: 'dandelion', displayName: 'Dandelion' },
    { codename: 'sunpod', displayName: 'Sun Pod' },
    { codename: 'redstinger', displayName: 'Red Stinger' },
    { codename: 'goldleaf', displayName: 'Gold Leaf' },
    { codename: 'sungun', displayName: 'Sungun' },
    { codename: 'akee', displayName: 'A.K.E.E.' },
    { codename: 'lavaguava', displayName: 'Lava Guava' },
    { codename: 'toadstool', displayName: 'Toadstool' },
    { codename: 'endurian', displayName: 'Endurian' },
    { codename: 'stallia', displayName: 'Stallia' },
    { codename: 'strawburst', displayName: 'Strawburst' },
    { codename: 'cactus', displayName: 'Cactus' },
    { codename: 'phatbeet', displayName: 'Phat Beet' },
    { codename: 'thymewarp', displayName: 'Thyme Warp' },
    { codename: 'celerystalker', displayName: 'Celery Stalker' },
    { codename: 'electricblueberry', displayName: 'Electric Blueberry' },
    { codename: 'sporeshroom', displayName: 'Spore-shroom' },
    { codename: 'garlic', displayName: 'Garlic' },
    { codename: 'intensivecarrot', displayName: 'Intensive Carrot' },
    { codename: 'jackolantern', displayName: "Jack O' Lantern" },
    { codename: 'primalpeashooter', displayName: 'Primal Peashooter' },
    { codename: 'grapeshot', displayName: 'Grapeshot' },
    { codename: 'primalwallnut', displayName: 'Primal Wall-nut' },
    { codename: 'perfumeshroom', displayName: 'Perfume-shroom' },
    { codename: 'coldsnapdragon', displayName: 'Cold Snapdragon' },
    { codename: 'primalsunflower', displayName: 'Primal Sunflower' },
    { codename: 'primalpotatomine', displayName: 'Primal Potato Mine' },
    { codename: 'shrinkingviolet', displayName: 'Shrinking Violet' },
    { codename: 'moonflower', displayName: 'Moonflower' },
    { codename: 'nightshade', displayName: 'Nightshade' },
    { codename: 'shadowshroom', displayName: 'Shadow-shroom' },
    { codename: 'bloominghearts', displayName: 'Blooming Heart' },
    { codename: 'escaperoot', displayName: 'Escape Root' },
    { codename: 'grimrose', displayName: 'Grimrose' },
    { codename: 'dusklobber', displayName: 'Dusk Lobber' },
    { codename: 'goldbloom', displayName: 'Gold Bloom' },
    { codename: 'electriccurrant', displayName: 'Electric Currant' },
    { codename: 'aloe', displayName: 'Aloe' },
    { codename: 'wasabiwhip', displayName: 'Wasabi Whip' },
    { codename: 'applemortar', displayName: 'Apple Mortar' },
    { codename: 'bombegranate', displayName: 'Bombegranate' },
    { codename: 'missiletoe', displayName: 'Missile Toe' },
    { codename: 'parsnip', displayName: 'Parsnip' },
    { codename: 'witchhazel', displayName: 'Witch Hazel' },
    { codename: 'hotdate', displayName: 'Hot Date' },
    { codename: 'caulipower', displayName: 'Caulipower' },
    { codename: 'solartomato', displayName: 'Solar Tomato' },
    { codename: 'electricpeashooter', displayName: 'Electric Peashooter' },
    { codename: 'hollyknight', displayName: 'Holly Barrier' },
    { codename: 'hollyshield', displayName: 'hollyshield' },
    { codename: 'hollybarrierleafplantfood', displayName: 'hollybarrierleafplantfood' },
    { codename: 'filamint', displayName: 'filamint' },
    { codename: 'peppermint', displayName: 'Pepper-mint' },
    { codename: 'wintermint', displayName: 'Winter-mint' },
    { codename: 'enlightenmint', displayName: 'Enlighten-mint' },
    { codename: 'reinforcemint', displayName: 'Reinforce-mint' },
    { codename: 'bombardmint', displayName: 'Bombard-mint' },
    { codename: 'ailmint', displayName: 'Ail-mint' },
    { codename: 'enchantmint', displayName: 'Enchant-mint' },
    { codename: 'containmint', displayName: 'Contain-mint' },
    { codename: 'enforcemint', displayName: 'Enforce-mint' },
    { codename: 'armamint', displayName: 'Arma-mint' },
    { codename: 'concealmint', displayName: 'Conceal-mint' },
    { codename: 'spearmint', displayName: 'Spear-mint' },
    { codename: 'shadowpeashooter', displayName: 'Shadow Peashooter' },
    { codename: 'poisonpeashooter', displayName: 'Goo Peashooter' },
    { codename: 'slingpea', displayName: 'Sling Pea' },
    { codename: 'appeasemint', displayName: 'Appease-mint' },
    { codename: 'minipeashooter', displayName: 'Mini Peashooter' },
    { codename: 'snappea', displayName: 'Snap Pea' },
    { codename: 'burnade', displayName: 'Burnade' },
    { codename: 'zoybeanpod', displayName: 'Zoybean Pod' },
    { codename: 'dazeychain', displayName: 'Dazey Chain' },
    { codename: 'electricitea', displayName: 'Electrici-tea' },
    { codename: 'blastberry', displayName: 'Blastberry Vine' },
    { codename: 'pokra', displayName: 'Pokra' },
    { codename: 'imppear', displayName: 'Imp Pear' },
    { codename: 'pumpkin', displayName: 'Pumpkin' },
    { codename: 'pyrevine', displayName: 'Pyre Vine' },
    { codename: 'icebloom', displayName: 'Ice Bloom' },
    { codename: 'dartichoke', displayName: 'Dartichoke' },
    { codename: 'ultomato', displayName: 'Ultomato' },
    { codename: 'gumnut', displayName: 'Gumnut' },
    { codename: 'shinevine', displayName: 'Shine Vine' },
    { codename: 'tumbleweed', displayName: 'Tumbleweed' },
    { codename: 'murkadamia', displayName: 'Murkadamia Nut' },
    { codename: 'puffball', displayName: 'Puffball' },
    { codename: 'stickybombrice', displayName: 'Stickybomb Rice' },
    { codename: 'olivepit', displayName: 'Olive Pit' },
    { codename: 'explodeovine', displayName: 'Explode-o-Vine' },
    { codename: 'turkeypult', displayName: 'Turkey-pult' },
    { codename: 'headbutter', displayName: 'Headbutter Lettuce' },
    { codename: 'boingsetta', displayName: 'Boingsetta' },
    { codename: 'hocus', displayName: 'Hocus Crocus' },
    { codename: 'gloomvine', displayName: 'Gloom Vine' },
    { codename: 'draftodil', displayName: 'Draftodil' },
    { codename: 'boomflower', displayName: 'Boom Balloon Flower' },
    { codename: 'pvine', displayName: 'Pea Vine' },
    { codename: 'inferno', displayName: 'Inferno' },
    { codename: 'solarsage', displayName: 'Solar Sage' },
    { codename: 'powervine', displayName: 'Power Vine' },
    { codename: 'noctarine', displayName: 'Noctarine' },
    { codename: 'noctarinecloud', displayName: 'Noctarine Cloud' },
    { codename: 'heathseeker', displayName: 'Heath Seeker' },
    { codename: 'iceweed', displayName: 'Iceweed' },
    { codename: 'tigergrass', displayName: 'Tiger Grass' },
    { codename: 'teleportatomine', displayName: 'Teleportato Mine' },
    { codename: 'buttercup', displayName: 'Buttercup' },
    { codename: 'blockoli', displayName: 'Blockoli' },
    { codename: 'bramblebush', displayName: 'Bramble Bush' },
    { codename: 'rhubarbarian', displayName: 'Rhubarbarian' },
    { codename: 'megagatling', displayName: 'Mega Gatling Pea' },
    { codename: 'levitater', displayName: 'Levitater' },
];
