export interface ZombieType {
    codename: string;
    displayName?: string;
}

export const Zombies: ZombieType[] = [
    { codename: 'tutorial', displayName: 'Basic Zombie' },
    { codename: 'tutorial_armor1', displayName: 'Conehead Zombie' },
    { codename: 'tutorial_armor2', displayName: 'Buckethead Zombie' },
    { codename: 'tutorial_armor4', displayName: 'Brickhead Zombie' },
    { codename: 'tutorial_balloon', displayName: 'tutorial_balloon' },
    { codename: 'tutorial_flag', displayName: 'Flag Zombie' },
    { codename: 'tutorial_flag_veteran', displayName: 'Rally Zombie' },
    { codename: 'mummy', displayName: 'Mummy Zombie' },
    { codename: 'mummy_armor1', displayName: 'Conehead Mummy' },
    { codename: 'mummy_armor2', displayName: 'Buckethead Mummy' },
    { codename: 'mummy_armor4', displayName: 'Pyramid-Head Zombie' },
    { codename: 'mummy_flag', displayName: 'Flag Mummy Zombie' },
    { codename: 'mummy_flag_veteran', displayName: 'Egypt Rally Zombie' },
    { codename: 'camel_almanac', displayName: 'Camel Zombies' },
    { codename: 'camel_onehump', displayName: 'Camel Zombies' },
    { codename: 'camel_twohump', displayName: 'Camel Zombies' },
    { codename: 'camel_manyhump', displayName: 'Camel Zombies' },
    { codename: 'camel_segment', displayName: 'Camel Zombies' },
    { codename: 'camel_onehump_touch', displayName: 'Camel Zombies' },
    { codename: 'camel_twohump_touch', displayName: 'Camel Zombies' },
    { codename: 'camel_manyhump_touch', displayName: 'Camel Zombies' },
    { codename: 'camel_segment_touch', displayName: 'Camel Zombies' },
    { codename: 'pharaoh', displayName: 'Pharaoh Zombie' },
    { codename: 'ra', displayName: 'Ra Zombie' },
    { codename: 'tomb_raiser', displayName: 'Tomb Raiser Zombie' },
    { codename: 'explorer', displayName: 'Explorer Zombie' },
    { codename: 'explorer_veteran', displayName: 'Torchlight Zombie' },
    { codename: 'pirate', displayName: 'Pirate Zombie' },
    { codename: 'pirate_armor1', displayName: 'Conehead Pirate' },
    { codename: 'pirate_armor2', displayName: 'Buckethead Pirate' },
    { codename: 'pirate_armor4', displayName: 'Barrelhead Zombie' },
    { codename: 'pirate_flag', displayName: 'Flag Pirate Zombie' },
    { codename: 'pirate_flag_veteran', displayName: 'Jolly Roger Zombie' },
    { codename: 'barrelroller', displayName: 'Barrel Roller Zombie' },
    { codename: 'cannon', displayName: 'Imp Cannon' },
    { codename: 'pirate_imp', displayName: 'Imp Pirate Zombie' },
    { codename: 'seagull', displayName: 'Seagull Zombie' },
    { codename: 'pelican', displayName: 'Pelican Zombie ' },
    { codename: 'pirate_captain', displayName: 'Pirate Captain Zombie' },
    { codename: 'pirate_captain_parrot', displayName: 'Zombie Parrot' },
    { codename: 'swashbuckler', displayName: 'Swashbuckler Zombie' },
    { codename: 'pirate_barrel', displayName: 'Pirate Barrel' },
    { codename: 'cowboy', displayName: 'Cowboy Zombie' },
    { codename: 'cowboy_armor1', displayName: 'Conehead Cowboy' },
    { codename: 'cowboy_armor2', displayName: 'Buckethead Cowboy' },
    { codename: 'cowboy_armor4', displayName: 'Cart-Head Zombie' },
    { codename: 'cowboy_flag', displayName: 'Flag Cowboy Zombie' },
    { codename: 'cowboy_flag_veteran', displayName: 'Cowboy Rally Zombie' },
    { codename: 'prospector', displayName: 'Prospector Zombie' },
    { codename: 'west_bullrider', displayName: 'Zombie Bull Rider' },
    { codename: 'west_bull', displayName: 'Zombie Bull' },
    { codename: 'west_bull_veteran', displayName: 'Rodeo Legend Zombie' },
    { codename: 'poncho', displayName: 'Poncho Zombie' },
    { codename: 'poncho_no_plate', displayName: 'Poncho Zombie' },
    { codename: 'poncho_plate', displayName: 'Poncho Zombie' },
    { codename: 'piano', displayName: 'Pianist Zombie' },
    { codename: 'chicken_farmer', displayName: 'Chicken Wrangler Zombie' },
    { codename: 'chicken', displayName: 'Zombie Chicken' },
    { codename: 'chicken_battlez', displayName: 'chicken_battlez' },
    { codename: 'mech_cone', displayName: 'Robo-Cone Zombie' },
    { codename: 'mech_cone_veteran', displayName: 'mech_cone_veteran' },
    { codename: 'football_mech', displayName: 'Mecha-Football Zombie' },
    { codename: 'disco_mech', displayName: 'Disco-tron 3000' },
    { codename: 'future', displayName: 'Future Zombie' },
    { codename: 'future_armor1', displayName: 'Future Conehead Zombie' },
    { codename: 'future_armor2', displayName: 'Future Buckethead Zombie' },
    { codename: 'future_armor4', displayName: 'Holo Head Zombie' },
    { codename: 'future_flag', displayName: 'Future Flag Zombie' },
    { codename: 'future_flag_veteran', displayName: 'Robo-Rally Zombie' },
    { codename: 'future_jetpack', displayName: 'Jetpack Zombie' },
    { codename: 'future_jetpack_veteran', displayName: 'Blastronaut Zombie' },
    { codename: 'future_jetpack_disco', displayName: 'Disco Jetpack Zombie' },
    { codename: 'future_gargantuar', displayName: 'Gargantuar Prime' },
    { codename: 'future_imp', displayName: 'Bug Bot Imp' },
    { codename: 'tutorial_gargantuar', displayName: 'Gargantuar' },
    { codename: 'tutorial_imp', displayName: 'Imp' },
    { codename: 'egypt_gargantuar', displayName: 'Mummified Gargantuar' },
    { codename: 'egypt_imp', displayName: 'Imp Mummy' },
    { codename: 'pirate_gargantuar', displayName: 'Gargantuar Pirate' },
    { codename: 'cowboy_gargantuar', displayName: 'Wild West Gargantuar' },
    { codename: 'future_protector', displayName: 'Shield Zombie' },
    { codename: 'future_protector_veteran', displayName: 'Deflector Zombie' },
    { codename: 'zombossmech_modern1', displayName: 'zombossmech_modern1' },
    { codename: 'zombossmech_future', displayName: 'Zombot Tomorrow-tron' },
    { codename: 'zombossmech_future2', displayName: 'zombossmech_future2' },
    { codename: 'zombossmech_future_battlez', displayName: 'zombossmech_future_battlez' },
    { codename: 'zombossmech_future_rift', displayName: 'zombossmech_future_rift' },
    { codename: 'zombossmech_egypt', displayName: 'Zombot Sphinx-inator' },
    { codename: 'zombossmech_egypt2', displayName: 'zombossmech_egypt2' },
    { codename: 'zombossmech_egypt_battlez', displayName: 'zombossmech_egypt_battlez' },
    { codename: 'zombossmech_egypt_rift', displayName: 'zombossmech_egypt_rift' },
    { codename: 'zombossmech_cowboy', displayName: 'Zombot War Wagon' },
    { codename: 'zombossmech_cowboy2', displayName: 'zombossmech_cowboy2' },
    { codename: 'zombossmech_cowboy_battlez', displayName: 'zombossmech_cowboy_battlez' },
    { codename: 'zombossmech_cowboy_rift', displayName: 'zombossmech_cowboy_rift' },
    { codename: 'zombossmech_pirate', displayName: 'Zombot Plank Walker' },
    { codename: 'zombossmech_pirate_battlez', displayName: 'zombossmech_pirate_battlez' },
    { codename: 'zombossmech_pirate_rift', displayName: 'zombossmech_pirate_rift' },
    { codename: 'zombossmech_pirate2', displayName: 'zombossmech_pirate2' },
    { codename: 'zombossmech_dark', displayName: 'Zombot Dark Dragon' },
    { codename: 'zombossmech_dark2', displayName: 'zombossmech_dark2' },
    { codename: 'zombossmech_dark_battlez', displayName: 'zombossmech_dark_battlez' },
    { codename: 'zombossmech_dark_rift', displayName: 'zombossmech_dark_rift' },
    { codename: 'zombossmech_beach', displayName: 'Zombot Sharktronic Sub' },
    { codename: 'zombossmech_beach_rift', displayName: 'zombossmech_beach_rift' },
    { codename: 'zombossmech_beach2', displayName: 'zombossmech_beach2' },
    { codename: 'zombossmech_iceage', displayName: 'Zombot Tuskmaster 10,000 BC' },
    { codename: 'zombossmech_iceage2', displayName: 'zombossmech_iceage2' },
    { codename: 'zombossmech_iceage_battlez', displayName: 'zombossmech_iceage_battlez' },
    { codename: 'zombossmech_iceage_battlez2', displayName: 'zombossmech_iceage_battlez2' },
    { codename: 'zombossmech_iceage_battlez3', displayName: 'zombossmech_iceage_battlez3' },
    { codename: 'zombossmech_iceage_rift', displayName: 'zombossmech_iceage_rift' },
    { codename: 'zombossmech_lostcity', displayName: 'Zombot Aerostatic Gondola' },
    { codename: 'zombossmech_lostcity2', displayName: 'zombossmech_lostcity2' },
    { codename: 'zombossmech_lostcity_battlez', displayName: 'zombossmech_lostcity_battlez' },
    { codename: 'zombossmech_lostcity_rift', displayName: 'zombossmech_lostcity_rift' },
    { codename: 'zombossmech_eighties', displayName: 'Zombot Multi-stage Masher' },
    { codename: 'zombossmech_eighties2', displayName: 'zombossmech_eighties2' },
    { codename: 'zombossmech_eighties_rift', displayName: 'zombossmech_eighties_rift' },
    { codename: 'zombossmech_eighties_battlez', displayName: 'zombossmech_eighties_battlez' },
    { codename: 'zombossmech_dino', displayName: 'Zombot Dinotronic Mechasaur' },
    { codename: 'zombossmech_dino2', displayName: 'zombossmech_dino2' },
    { codename: 'zombossmech_dino_battlez', displayName: 'zombossmech_dino_battlez' },
    { codename: 'zombossmech_dino_rift', displayName: 'zombossmech_dino_rift' },
    { codename: 'zombossmech_modern_egypt', displayName: 'zombossmech_modern_egypt' },
    { codename: 'zombossmech_modern_pirate', displayName: 'zombossmech_modern_pirate' },
    { codename: 'zombossmech_modern_cowboy', displayName: 'zombossmech_modern_cowboy' },
    { codename: 'zombossmech_modern_future', displayName: 'zombossmech_modern_future' },
    { codename: 'zombossmech_modern_dark', displayName: 'zombossmech_modern_dark' },
    { codename: 'zombossmech_modern_beach', displayName: 'zombossmech_modern_beach' },
    { codename: 'zombossmech_modern_iceage', displayName: 'zombossmech_modern_iceage' },
    { codename: 'zombossmech_modern_lostcity', displayName: 'zombossmech_modern_lostcity' },
    { codename: 'zombossmech_modern_eighties', displayName: 'zombossmech_modern_eighties' },
    { codename: 'zombossmech_modern_dino', displayName: 'zombossmech_modern_dino' },
    { codename: 'cleopatra', displayName: 'cleopatra' },
    { codename: 'treasureyeti', displayName: 'Treasure Yeti' },
    { codename: 'joustyeti', displayName: 'joustyeti' },
    { codename: 'dark', displayName: 'Peasant Zombie' },
    { codename: 'dark_armor1', displayName: 'Conehead Peasant' },
    { codename: 'dark_armor2', displayName: 'Buckethead Peasant' },
    { codename: 'dark_flag', displayName: 'Peasant Flag Zombie' },
    { codename: 'dark_flag_veteran', displayName: 'dark_flag_veteran' },
    { codename: 'dark_armor3', displayName: 'Knight Zombie' },
    { codename: 'dark_armor4', displayName: 'dark_armor4' },
    { codename: 'dark_imp', displayName: 'Imp Monk Zombie' },
    { codename: 'dark_imp_dragon', displayName: 'Imp Dragon Zombie' },
    { codename: 'dark_gargantuar', displayName: 'Dark Ages Gargantuar' },
    { codename: 'dark_wizard', displayName: 'Wizard Zombie' },
    { codename: 'dark_wizard_veteran', displayName: 'dark_wizard_veteran' },
    { codename: 'dark_juggler', displayName: 'Jester Zombie' },
    { codename: 'dark_king', displayName: 'Zombie King' },
    { codename: 'holiday_gargantuar', displayName: 'holiday_gargantuar' },
    { codename: 'holiday_imp', displayName: 'holiday_imp' },
    { codename: 'leprachaun_imp', displayName: 'leprachaun_imp' },
    { codename: 'spring', displayName: 'spring' },
    { codename: 'spring_armor1', displayName: 'spring_armor1' },
    { codename: 'spring_armor2', displayName: 'spring_armor2' },
    { codename: 'spring_flag', displayName: 'spring_flag' },
    { codename: 'spring_camel_onehump', displayName: 'Camel Zombies' },
    { codename: 'spring_camel_twohump', displayName: 'Camel Zombies' },
    { codename: 'spring_camel_manyhump', displayName: 'Camel Zombies' },
    { codename: 'spring_camel_segment', displayName: 'Camel Zombies' },
    { codename: 'spring_poncho', displayName: 'spring_poncho' },
    { codename: 'spring_wizard', displayName: 'spring_wizard' },
    { codename: 'spring_gargantuar', displayName: 'spring_gargantuar' },
    { codename: 'spring_gargantuar_af', displayName: 'spring_gargantuar_af' },
    { codename: 'spring_imp', displayName: 'spring_imp' },
    { codename: 'spring_imp_af', displayName: 'spring_imp_af' },
    { codename: 'halloween', displayName: 'halloween' },
    { codename: 'halloween_armor1', displayName: 'halloween_armor1' },
    { codename: 'halloween_armor2', displayName: 'halloween_armor2' },
    { codename: 'halloween_flag', displayName: 'halloween_flag' },
    { codename: 'halloween_gargantuar', displayName: 'halloween_gargantuar' },
    { codename: 'halloween_imp', displayName: 'halloween_imp' },
    { codename: 'halloween_camel_twohump', displayName: 'Camel Zombies' },
    { codename: 'foodfight', displayName: 'foodfight' },
    { codename: 'foodfight_armor1', displayName: 'foodfight_armor1' },
    { codename: 'foodfight_armor2', displayName: 'foodfight_armor2' },
    { codename: 'foodfight_flag', displayName: 'foodfight_flag' },
    { codename: 'foodfight_chefster', displayName: 'foodfight_chefster' },
    { codename: 'foodfight_gobbler_king', displayName: 'foodfight_gobbler_king' },
    { codename: 'foodfight_turkey', displayName: 'foodfight_turkey' },
    { codename: 'foodfight_turkey_battlez', displayName: 'foodfight_turkey_battlez' },
    { codename: 'foodfight_turkey_boss', displayName: 'foodfight_turkey_boss' },
    { codename: 'feastivus', displayName: 'feastivus' },
    { codename: 'feastivus_armor1', displayName: 'feastivus_armor1' },
    { codename: 'feastivus_armor2', displayName: 'feastivus_armor2' },
    { codename: 'feastivus_flag', displayName: 'feastivus_flag' },
    { codename: 'feastivus_gargantuar', displayName: 'feastivus_gargantuar' },
    { codename: 'feastivus_imp', displayName: 'feastivus_imp' },
    { codename: 'feastivus_camel_onehump', displayName: 'Camel Zombies' },
    { codename: 'feastivus_camel_twohump', displayName: 'Camel Zombies' },
    { codename: 'feastivus_camel_manyhump', displayName: 'Camel Zombies' },
    { codename: 'feastivus_camel_segment', displayName: 'Camel Zombies' },
    { codename: 'feastivus_swashbuckler', displayName: 'feastivus_swashbuckler' },
    { codename: 'feastivus_poncho', displayName: 'feastivus_poncho' },
    { codename: 'feastivus_piano', displayName: 'feastivus_piano' },
    { codename: 'easter_troglobite', displayName: 'easter_troglobite' },
    { codename: 'easter_troglobite_1block', displayName: 'easter_troglobite_1block' },
    { codename: 'easter_troglobite_2block', displayName: 'easter_troglobite_2block' },
    { codename: 'feastivus_troglobite', displayName: 'feastivus_troglobite' },
    { codename: 'feastivus_troglobite_1block', displayName: 'feastivus_troglobite_1block' },
    { codename: 'feastivus_troglobite_2block', displayName: 'feastivus_troglobite_2block' },
    { codename: 'pet', displayName: 'pet' },
    { codename: 'beach', displayName: 'Pompadour Zombie' },
    { codename: 'beach_armor1', displayName: 'Pompadour Conehead' },
    { codename: 'beach_armor2', displayName: 'Pompadour Buckethead' },
    { codename: 'beach_flag', displayName: 'Beach Flag Zombie' },
    { codename: 'beach_fem', displayName: 'Bikini Zombie' },
    { codename: 'beach_fem_armor1', displayName: 'Bikini Conehead' },
    { codename: 'beach_fem_armor2', displayName: 'Bikini Buckethead' },
    { codename: 'beach_snorkel', displayName: 'Snorkel Zombie' },
    { codename: 'beach_surfer', displayName: 'Surfer Zombie' },
    { codename: 'beach_fastswimmer', displayName: 'beach_fastswimmer' },
    { codename: 'beach_imp', displayName: 'Imp Mermaid Zombie' },
    { codename: 'beach_gargantuar', displayName: 'Deep Sea Gargantuar' },
    { codename: 'beach_fisherman', displayName: 'Fisherman Zombie ' },
    { codename: 'beach_octopus', displayName: 'Octo Zombie' },
    { codename: 'iceage', displayName: 'Cave Zombie' },
    { codename: 'iceage_armor1', displayName: 'Cave Conehead Zombie' },
    { codename: 'iceage_armor2', displayName: 'Cave Buckethead Zombie' },
    { codename: 'iceage_armor3', displayName: 'Blockhead Zombie' },
    { codename: 'iceage_flag', displayName: 'Cave Flag Zombie' },
    { codename: 'iceage_imp', displayName: 'Yeti Imp' },
    { codename: 'iceage_gargantuar', displayName: 'Sloth Gargantuar' },
    { codename: 'iceage_hunter', displayName: 'Hunter Zombie' },
    { codename: 'iceage_dodo', displayName: 'Dodo Rider Zombie' },
    { codename: 'iceage_weaselhoarder', displayName: 'Weasel Hoarder' },
    { codename: 'iceage_weasel', displayName: 'Ice Weasel' },
    { codename: 'iceage_troglobite', displayName: 'Troglobite' },
    { codename: 'iceage_troglobite_2block', displayName: 'Troglobite' },
    { codename: 'iceage_troglobite_1block', displayName: 'Troglobite' },
    { codename: 'lostcity_impporter', displayName: 'Imp Porter' },
    { codename: 'lostcity_excavator', displayName: 'Excavator Zombie' },
    { codename: 'lostcity', displayName: 'Adventurer Zombie' },
    { codename: 'lostcity_armor1', displayName: 'Conehead Adventurer Zombie' },
    { codename: 'lostcity_armor2', displayName: 'Buckethead Adventurer Zombie' },
    { codename: 'lostcity_flag', displayName: 'Flag Adventurer Zombie' },
    { codename: 'lostcity_jane', displayName: 'Parasol Zombie' },
    { codename: 'lostcity_lostpilot', displayName: 'Lost Pilot Zombie' },
    { codename: 'lostcity_bug', displayName: 'Bug Zombie' },
    { codename: 'lostcity_bug_armor1', displayName: 'Bug Zombie' },
    { codename: 'lostcity_bug_armor2', displayName: 'Bug Zombie' },
    { codename: 'lostcity_crystalskull', displayName: 'Turquoise Skull Zombie' },
    { codename: 'lostcity_imp', displayName: 'Lost City Imp Zombie' },
    { codename: 'lostcity_gargantuar', displayName: 'Porter Gargantuar' },
    { codename: 'lostcity_relichunter', displayName: 'Relic Hunter Zombie' },
    { codename: 'eighties', displayName: 'Neon Zombie' },
    { codename: 'eighties_armor1', displayName: 'Neon Conehead' },
    { codename: 'eighties_armor2', displayName: 'Neon Buckethead' },
    { codename: 'eighties_8bit', displayName: '8-Bit Zombie' },
    { codename: 'eighties_8bit_armor1', displayName: '8-Bit Zombie' },
    { codename: 'eighties_8bit_armor2', displayName: '8-Bit Zombie' },
    { codename: 'eighties_flag', displayName: 'Neon Flag Zombie' },
    { codename: 'eighties_imp', displayName: 'Impunk' },
    { codename: 'eighties_gargantuar', displayName: 'Hair Metal Gargantuar' },
    { codename: 'eighties_punk', displayName: 'Punk Zombie' },
    { codename: 'eighties_mc', displayName: 'MC Zom-B' },
    { codename: 'eighties_breakdancer', displayName: 'Breakdancer Zombie' },
    { codename: 'eighties_glitter', displayName: 'Glitter Zombie' },
    { codename: 'eighties_boombox', displayName: 'Boombox Zombie' },
    { codename: 'eighties_arcade', displayName: 'Arcade Zombie' },
    { codename: 'dino', displayName: 'Jurassic Zombie' },
    { codename: 'dino_armor1', displayName: 'Jurassic Conehead' },
    { codename: 'dino_armor2', displayName: 'Jurassic Buckethead' },
    { codename: 'dino_armor3', displayName: 'Jurassic Fossilhead' },
    { codename: 'dino_armor4', displayName: 'Amberhead Zombie' },
    { codename: 'dino_bully', displayName: 'Jurassic Bully' },
    { codename: 'dino_bully_veteran', displayName: 'Jurassic Rockpuncher' },
    { codename: 'dino_flag', displayName: 'Jurassic Flag Zombie' },
    { codename: 'dino_flag_veteran', displayName: 'Jurassic Rally Zombie' },
    { codename: 'dino_imp', displayName: 'Jurassic Imp' },
    { codename: 'dino_gargantuar', displayName: 'Jurassic Gargantuar' },
    { codename: 'modern_newspaper', displayName: 'Newspaper Zombie' },
    { codename: 'newspaper_veteran', displayName: 'Sunday Edition Zombie' },
    { codename: 'modern_balloon', displayName: 'Balloon Zombie' },
    { codename: 'modern_allstar', displayName: 'All-Star Zombie' },
    { codename: 'modern_superfanimp', displayName: 'Super-Fan Imp' },
    { codename: 'vase_gargantuar', displayName: 'Vase Gargantuar' },
    { codename: 'hamster_ball', displayName: 'hamster_ball' },
    { codename: 'valentines', displayName: 'valentines' },
    { codename: 'valentines_armor1', displayName: 'valentines_armor1' },
    { codename: 'valentines_armor2', displayName: 'valentines_armor2' },
    { codename: 'valentines_flag', displayName: 'valentines_flag' },
    { codename: 'valentines_gargantuar', displayName: 'valentines_gargantuar' },
    { codename: 'valentines_imp', displayName: 'valentines_imp' },
    { codename: 'leprachaun_dodo', displayName: 'leprachaun_dodo' },
    { codename: 'stpatrick', displayName: 'stpatrick' },
    { codename: 'stpatrick_armor1', displayName: 'stpatrick_armor1' },
    { codename: 'stpatrick_armor2', displayName: 'stpatrick_armor2' },
    { codename: 'birthday', displayName: 'birthday' },
    { codename: 'birthday_flag', displayName: 'birthday_flag' },
    { codename: 'birthday_barrel', displayName: 'birthday_barrel' },
    { codename: 'birthday_gargantuar', displayName: 'birthday_gargantuar' },
    { codename: 'birthday_pharaoh', displayName: 'birthday_pharaoh' },
    { codename: 'birthday_juggler', displayName: 'birthday_juggler' },
    { codename: 'birthday_troglobite', displayName: 'birthday_troglobite' },
    { codename: 'birthday_troglobite_2block', displayName: 'birthday_troglobite_2block' },
    { codename: 'birthday_troglobite_1block', displayName: 'birthday_troglobite_1block' },
    { codename: 'birthday_jetpack', displayName: 'birthday_jetpack' },
    { codename: 'summer_basic', displayName: 'summer_basic' },
    { codename: 'summer_armor1', displayName: 'summer_armor1' },
    { codename: 'summer_armor2', displayName: 'summer_armor2' },
    { codename: 'summer_flag', displayName: 'summer_flag' },
    { codename: 'summer_bug', displayName: 'summer_bug' },
    { codename: 'summer_bug_armor1', displayName: 'Bug Zombie' },
    { codename: 'summer_bug_armor2', displayName: 'Bug Zombie' },
    { codename: 'summer_gargantuar', displayName: 'summer_gargantuar' },
    { codename: 'summer_imp', displayName: 'summer_imp' },
    { codename: 'beghouled', displayName: 'beghouled' },
    { codename: 'beghouled_armor1', displayName: 'beghouled_armor1' },
    { codename: 'beghouled_armor2', displayName: 'beghouled_armor2' },
    { codename: 'beghouled_newspaper', displayName: 'beghouled_newspaper' },
    { codename: 'beghouled_mummy', displayName: 'beghouled_mummy' },
    { codename: 'beghouled_mummy_armor1', displayName: 'beghouled_mummy_armor1' },
    { codename: 'beghouled_mummy_armor2', displayName: 'beghouled_mummy_armor2' },
    { codename: 'beghouled_pirate', displayName: 'beghouled_pirate' },
    { codename: 'beghouled_pirate_armor1', displayName: 'beghouled_pirate_armor1' },
    { codename: 'beghouled_pirate_armor2', displayName: 'beghouled_pirate_armor2' },
    { codename: 'beghouled_cowboy', displayName: 'beghouled_cowboy' },
    { codename: 'beghouled_cowboy_armor1', displayName: 'beghouled_cowboy_armor1' },
    { codename: 'beghouled_cowboy_armor2', displayName: 'beghouled_cowboy_armor2' },
    { codename: 'beghouled_future', displayName: 'beghouled_future' },
    { codename: 'beghouled_future_armor1', displayName: 'beghouled_future_armor1' },
    { codename: 'beghouled_future_armor2', displayName: 'beghouled_future_armor2' },
    { codename: 'beghouled_dark', displayName: 'beghouled_dark' },
    { codename: 'beghouled_dark_armor1', displayName: 'beghouled_dark_armor1' },
    { codename: 'beghouled_dark_armor2', displayName: 'beghouled_dark_armor2' },
    { codename: 'beghouled_beach', displayName: 'beghouled_beach' },
    { codename: 'beghouled_beach_armor1', displayName: 'beghouled_beach_armor1' },
    { codename: 'beghouled_beach_armor2', displayName: 'beghouled_beach_armor2' },
    { codename: 'beghouled_beach_fem', displayName: 'beghouled_beach_fem' },
    { codename: 'beghouled_beach_fem_armor1', displayName: 'beghouled_beach_fem_armor1' },
    { codename: 'beghouled_beach_fem_armor2', displayName: 'beghouled_beach_fem_armor2' },
    { codename: 'beghouled_iceage', displayName: 'beghouled_iceage' },
    { codename: 'beghouled_iceage_armor1', displayName: 'beghouled_iceage_armor1' },
    { codename: 'beghouled_iceage_armor2', displayName: 'beghouled_iceage_armor2' },
    { codename: 'beghouled_lostcity', displayName: 'beghouled_lostcity' },
    { codename: 'beghouled_lostcity_armor1', displayName: 'beghouled_lostcity_armor1' },
    { codename: 'beghouled_lostcity_armor2', displayName: 'beghouled_lostcity_armor2' },
    { codename: 'hero_electricboogaloo', displayName: 'hero_electricboogaloo' },
    { codename: 'hero_impfinity', displayName: 'hero_impfinity' },
    { codename: 'hero_rustbolt', displayName: 'hero_rustbolt' },
    { codename: 'hero_smash', displayName: 'hero_smash' },
    { codename: 'hero_superbrainz', displayName: 'hero_superbrainz' },
    { codename: 'hero_barrelroller', displayName: 'hero_barrelroller' },
    { codename: 'hero_barrel', displayName: 'hero_barrel' },
    { codename: 'bighead_allstar', displayName: 'bighead_allstar' },
    { codename: 'bighead_balloon', displayName: 'bighead_balloon' },
    { codename: 'bighead_newspaper', displayName: 'bighead_newspaper' },
    { codename: 'bighead_superfan', displayName: 'bighead_superfan' },
    { codename: 'bighead_flag', displayName: 'bighead_flag' },
    { codename: 'bighead', displayName: 'bighead' },
    { codename: 'bighead_armor1', displayName: 'bighead_armor1' },
    { codename: 'bighead_armor2', displayName: 'bighead_armor2' },
    { codename: 'bighead_gargantuar', displayName: 'bighead_gargantuar' },
    { codename: 'bighead_imp', displayName: 'bighead_imp' },
    { codename: 'bighead_barrelroller', displayName: 'bighead_barrelroller' },
    { codename: 'bighead_barrel', displayName: 'bighead_barrel' },
    { codename: 'general_treadmill_phase1', displayName: 'general_treadmill_phase1' },
    { codename: 'general_treadmill_phase2', displayName: 'general_treadmill_phase2' },
    { codename: 'general_treadmill_phase3', displayName: 'Cardio Zombie' },
    { codename: 'general_zmech_phase1', displayName: 'general_zmech_phase1' },
    { codename: 'general_zmech_phase2', displayName: 'general_zmech_phase2' },
    { codename: 'general_zmech_phase3', displayName: 'Z-Mech' },
    { codename: 'zoybeanpod_gargantuar', displayName: 'zoybeanpod_gargantuar' },
    { codename: 'zoybeanpod_basic', displayName: 'zoybeanpod_basic' },
    { codename: 'zoybeanpod_armor1', displayName: 'zoybeanpod_armor1' },
    { codename: 'zoybeanpod_armor2', displayName: 'zoybeanpod_armor2' },
    { codename: 'caketank', displayName: '#caketank' },
    { codename: 'imppear_imp', displayName: 'Imp Pear Imp' },
    { codename: 'roman', displayName: 'Roman Zombie' },
    { codename: 'roman_armor1', displayName: 'Roman Conehead' },
    { codename: 'roman_armor2', displayName: 'Roman Buckethead' },
    { codename: 'roman_armor3', displayName: 'Centurion Zombie' },
    { codename: 'roman_armor4', displayName: 'Bust Head Zombie' },
    { codename: 'roman_flag', displayName: 'Roman Flag Zombie' },
    { codename: 'roman_healer', displayName: 'Healer Zombie' },
    { codename: 'roman_shield_almanac', displayName: 'Roman Shield Zombie' },
    { codename: 'roman_shield_triad', displayName: 'Roman Shield Zombie' },
    { codename: 'roman_shield_pair', displayName: 'Roman Shield Zombie' },
    { codename: 'roman_segment', displayName: 'Roman Shield Zombie' },
    { codename: 'roman_shield_top', displayName: 'Roman Shield Zombie' },
    { codename: 'roman_gargantuar', displayName: 'Gladiator Gargantuar' },
    { codename: 'roman_imp', displayName: 'Roman Imp' },
    { codename: 'roman_ballista', displayName: 'Zcorpion Zombie' },
    { codename: 'gum', displayName: 'gum' },
    { codename: 'general_caesar_phase1', displayName: 'general_caesar_phase1' },
    { codename: 'general_caesar_phase2', displayName: 'general_caesar_phase2' },
    { codename: 'general_caesar_phase3', displayName: 'Roman Caesar Zombie' },
    { codename: 'roman_medusa', displayName: 'Zombie Medusa' },
    { codename: 'zombie_statue', displayName: 'zombie_statue' },
    { codename: 'zcorp_gargantuar', displayName: 'Head Office Impgantuar' },
    { codename: 'zcorp_imp', displayName: 'Gargimp Legal' },
    { codename: 'zcorp', displayName: 'ZCorp New Hire' },
    { codename: 'zcorp_armor1', displayName: 'ZCorp Conehead' },
    { codename: 'zcorp_armor2', displayName: 'ZCorp Buckethead' },
    { codename: 'zcorp_fem', displayName: 'ZCorp Contractor' },
    { codename: 'zcorp_fem_armor1', displayName: 'ZCorp Contractor Conehead' },
    { codename: 'zcorp_fem_armor2', displayName: 'ZCorp Contractor Buckethead' },
    { codename: 'zcorp_flag', displayName: 'ZCorp Flag Zombie' },
    { codename: 'turkeypult_basic', displayName: 'turkeypult_basic' },
    { codename: 'turkeypult_turkzilla', displayName: 'turkeypult_turkzilla' },
    { codename: 'zcorp_consultant', displayName: 'ZCorp Consultant' },
    { codename: 'zcorp_helpdesk', displayName: 'ZCorp HelpDesk' },
    { codename: 'solarsage_enlightened', displayName: 'solarsage_enlightened' },
    { codename: 'zcorp_racer_chair', displayName: 'ZCorp Chair Racer' },
    { codename: 'zcorp_racer', displayName: 'zcorp_racer' },
    { codename: 'tigergrass_tiger', displayName: 'tigergrass_tiger' },
    { codename: 'carnie', displayName: 'Carnie Zombie' },
    { codename: 'carnie_armor1', displayName: 'Carnie Conehead' },
    { codename: 'carnie_armor2', displayName: 'Carnie Buckethead' },
    { codename: 'carnie_flag', displayName: 'Carnie Flag Zombie' },
    { codename: 'carnie_cannon', displayName: 'Carnie Cannon' },
    { codename: 'carnie_imp', displayName: 'Carnie Imp' },
    { codename: 'carnie_imp_twins', displayName: 'Carnie Imp Twins' },
    { codename: 'carnie_imp_split', displayName: 'Carnie Imp Split' },
    { codename: 'carnie_gargantuar', displayName: 'Strongman Gargantuar' },
    { codename: 'carnie_armor4', displayName: 'Grinderhead Zombie' },
    { codename: 'carnie_monkey', displayName: 'carnie_monkey' },
    { codename: 'carnie_magician', displayName: 'Magician Zombie' },
    { codename: 'carnie_firebreather', displayName: 'Firebreather Zombie' },
    { codename: 'carnie_dove', displayName: 'carnie_dove' },
    { codename: 'carnie_stiltwalker', displayName: 'Stiltwalker Zombie' },
    { codename: 'zombossmech_circus', displayName: 'Zombot Catastro-liope' },
    { codename: 'zombossmech_circus_battlez', displayName: 'zombossmech_circus_battlez' },
    { codename: 'zombossmech_circus_rift', displayName: 'zombossmech_circus_rift' },
    { codename: 'lunar', displayName: 'lunar' },
    { codename: 'lunar_armor1', displayName: 'lunar_armor1' },
    { codename: 'lunar_armor2', displayName: 'lunar_armor2' },
    { codename: 'lunar_flag', displayName: 'lunar_flag' },
    { codename: 'lunar_superfanimp', displayName: 'lunar_superfanimp' },
    { codename: 'lunar_camel_onehump', displayName: 'Camel Zombies' },
    { codename: 'lunar_camel_twohump', displayName: 'Camel Zombies' },
    { codename: 'lunar_camel_manyhump', displayName: 'Camel Zombies' },
    { codename: 'lunar_camel_segment', displayName: 'Camel Zombies' },
    { codename: 'sportzball_buckethead', displayName: 'sportzball_buckethead' },
    { codename: 'sportzball_balloon', displayName: 'sportzball_balloon' },
    { codename: 'sportzball_wizard', displayName: 'sportzball_wizard' },
    { codename: 'sportzball_imp', displayName: 'sportzball_imp' },
    { codename: 'sportzball_gargantuar', displayName: 'sportzball_gargantuar' },
];

export const ZombieDisplayNames = Object.fromEntries(Zombies.map((zombie) => [zombie.codename, zombie.displayName]));
